### ISSUE TITLE
Using releases/tags

### ISSUE THREAD

**Issue by phedoreanu** [toshirot/ccchart#16]
Hello,

Greate work on this library, but bower has some problems installing it:
```sh
bower                            retry Request to https://bower.herokuapp.com/packages/ccchart failed with ETIMEDOUT, retrying in 1.9s
bower                            retry Request to https://bower.herokuapp.com/packages/ccchart failed with ETIMEDOUT, retrying in 3.1s
bower ccchart#~1.11.06      not-cached git://github.com/toshirot/ccchart.git#~1.11.06
bower ccchart#~1.11.06         resolve git://github.com/toshirot/ccchart.git#~1.11.06
bower ccchart#~1.11.06    ENORESTARGET Tag/branch ~1.11.06 does not exist
```
Can you please create a release/tag for the (new) versions released? That will solve the problems!

Thank you

**Comment by toshirot** [comment]
thanx phedoreanu. but, 
since I have never wrote the tag , I do not know how to do . I will take a look .

**Comment by phedoreanu** [comment]
https://help.github.com/articles/creating-releases/

:+1:

**Comment by toshirot** [comment]
thank you phedoreanu :) 
https://github.com/toshirot/ccchart/releases/tag/v1.11.06

test:
$ bower i ccchart#v1.11.06
bower cached        git://github.com/toshirot/ccchart.git#v1.11.06
bower validate      v1.11.06 against git://github.com/toshirot/ccchart.git#v1.11.06
bower install       ccchart#v1.11.06

ccchart#v1.11.06 bower_components/ccchart

**Comment by phedoreanu** [comment]
Brilliant! 

Cheers! :+1:
